#!/bin/sh

printf "\n"
printf "                       _ _        \n"
printf "     /\               | | |       \n"
printf "    /  \   _ __   ___ | | | ___   \n"
printf "   / /\ \ | '_ \ / _ \| | |/ _ \  \n"
printf "  / ____ \| |_) | (_) | | | (_) | \n"
printf " /_/    \_\ .__/ \___/|_|_|\___/  \n"
printf "          | |                     \n"
printf "          |_|                     \n"
printf "\n"
printf " >> https://github.com/apollo-black/apollo-dev-vm\n"
printf " >> https://apollo.black\n\n"
